# Generated by Django 4.2 on 2023-06-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustration',
            name='type',
            field=models.CharField(choices=[('tattoos', 'Татуировки'), ('eyebrow', 'Брови'), ('eaves', 'Веки'), ('lips', 'Губы'), ('process', 'Процесс')], default='tattoos', help_text='Тип процедуры', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='img',
            field=models.ImageField(upload_to='illustration', verbose_name='Изображение'),
        ),
    ]
